vhd: Fix crypto link errors
libvhd fails to link with:
/usr/bin/ld: .libs/vhd-util-key.o:blktap/vhd/lib/vhd-util-key.c:55: multiple definition of `crypto_handle'; .libs/vhd-util-copy.o:blktap/vhd/lib/vhd-util-copy.c:59: first defined here
/usr/bin/ld: .libs/vhd-util-key.o:blktap/vhd/lib/vhd-util-key.c:54: multiple definition of `pvhd_calculate_keyhash'; .libs/vhd-util-copy.o:blktap/vhd/lib/vhd-util-copy.c:56: first defined here

Make the crypto variables in vhd-util-copy.c and vhd-util-key.c static
to fix the error.

The other option would be to factor out the common code.  However each
file seems to expect its own copy, so sharing them could lead to
unexpected results.

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>